/** Design tokens extracted from design/DESIGN.md (Sabor Ahogado & Tradición Michoacana). */
module.exports = {
  content: [
    './index.html',
    './menu/**/*.html',
    './ubicacion/**/*.html',
    './contacto/**/*.html',
    './admin/catalogo/**/*.html',
    './admin/pedidos/**/*.html',
    './admin/config-envio/**/*.html',
    './cuenta/rastreo/**/*.html',
    './cuenta/perfil/**/*.html',
    './cuenta/historial/**/*.html',
    './src/js/**/*.js'
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fbf8fc',
        'surface-dim': '#dcd9dd',
        'surface-bright': '#fbf8fc',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f6f2f7',
        'surface-container': '#f0edf1',
        'surface-container-high': '#eae7eb',
        'surface-container-highest': '#e4e1e6',
        'on-surface': '#1b1b1e',
        'on-surface-variant': '#5b403d',
        'inverse-surface': '#303033',
        'inverse-on-surface': '#f3f0f4',
        outline: '#8f6f6c',
        'outline-variant': '#e4beb9',
        primary: '#93000b',
        'on-primary': '#ffffff',
        'primary-container': '#b91c1c',
        'on-primary-container': '#ffcdc7',
        'primary-fixed': '#ffdad6',
        'primary-fixed-dim': '#ffb4ab',
        'on-primary-fixed': '#410002',
        'on-primary-fixed-variant': '#93000b',
        secondary: '#904d00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fe932c',
        'on-secondary-container': '#663500',
        'secondary-fixed': '#ffdcc3',
        'secondary-fixed-dim': '#ffb77d',
        'on-secondary-fixed': '#2f1500',
        'on-secondary-fixed-variant': '#6e3900',
        tertiary: '#005223',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#006d30',
        'on-tertiary-container': '#8bed9d',
        'tertiary-fixed': '#95f8a7',
        'tertiary-fixed-dim': '#79db8d',
        'on-tertiary-fixed': '#00210a',
        'on-tertiary-fixed-variant': '#005323',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fbf8fc',
        'on-background': '#1b1b1e',
        'surface-variant': '#e4e1e6',
        'crema-bg': '#FDFBF7',
        'crema-surface': '#F7F3EA',
        'chile-dark': '#7F1D1D',
        'mustard-light': '#FEF3C7',
        'whatsapp-green': '#25D366'
      },
      fontFamily: {
        'display-hero': ['Epilogue', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'headline-md': ['Epilogue', 'sans-serif'],
        'headline-sm': ['Epilogue', 'sans-serif'],
        'price-lg': ['Epilogue', 'sans-serif'],
        'price-md': ['Epilogue', 'sans-serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif']
      },
      fontSize: {
        'display-hero': ['48px', { lineHeight: '54px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-hero-mobile': ['34px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'headline-lg-mobile': ['26px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['22px', { lineHeight: '28px', fontWeight: '700' }],
        'headline-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['15px', { lineHeight: '22px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'price-lg': ['24px', { lineHeight: '28px', fontWeight: '800' }],
        'price-md': ['18px', { lineHeight: '22px', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '18px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }]
      },
      spacing: {
        gutter: '1rem',
        'gutter-desktop': '1.5rem',
        margin: '1rem',
        'margin-desktop': '2.5rem',
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem'
      },
      borderRadius: {
        DEFAULT: '0.5rem',
        sm: '0.25rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px'
      }
    }
  },
  plugins: []
};
